### ISSUE TITLE
bug:fix responsiveness

### ISSUE THREAD

**Issue by sameeramjad07** [sameeramjad07/CODSOFT-Task-1#1]
The titles are not appearing correctly on mobile so you need to fix that

**Comment by pt21v** [comment]
Hi @sameeramjad07 , assign to me, please!

**Comment by sameeramjad07** [comment]
> Hi @sameeramjad07 , assign to me, please!

Hey thankyou for your interest but this has already been assigned to someone else

**Comment by pt21v** [comment]
I see. Thank you, @sameeramjad07 !
